# Generated by Django 6.0.1 on 2026-01-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delivery_sms_sent_delivery_sms_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='weight_kg',
            new_name='cherry_kg',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='liters',
            new_name='kg_dry',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='price_per_liter',
            new_name='price_per_kg',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='total_liters',
            new_name='total_kg_dry',
        ),
    ]
