# Generated by Django 6.0.1 on 2026-01-12 11:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_weight_kg_delivery_cherry_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('120.00'), max_digits=6),
        ),
    ]
